// src/context/MusicContext.js                                                                                                                                                                                    
import React, { createContext, useState, useContext } from 'react';                                                                                                                                               
import axios from 'axios';                                                                                                                                                                                        
                                                                                                                                                                                                                  
const MusicContext = createContext();                                                                                                                                                                             
                                                                                                                                                                                                                  
export function MusicProvider({ children }) {                                                                                                                                                                     
  const [searchResults, setSearchResults] = useState([]);                                                                                                                                                         
  const [recommendations, setRecommendations] = useState([]);                                                                                                                                                     
  const [loading, setLoading] = useState(false);                                                                                                                                                                  
  const [error, setError] = useState(null);                                                                                                                                                                       
                                                                                                                                                                                                                  
  const API_URL = 'http://10.105.10.80:8035';                                                                                                                                                                        
                                                                                                                                                                                                                  
  const searchSongs = async (query) => {                                                                                                                                                                          
    try {                                                                                                                                                                                                         
      setLoading(true);                                                                                                                                                                                           
      setError(null);                                                                                                                                                                                             
      const response = await axios.get(`${API_URL}/search?query=${query}`);                                                                                                                                       
      setSearchResults(response.data.results);                                                                                                                                                                    
    } catch (err) {                                                                                                                                                                                               
      setError('Failed to search songs');                                                                                                                                                                         
      console.error(err);                                                                                                                                                                                         
    } finally {                                                                                                                                                                                                   
      setLoading(false);                                                                                                                                                                                          
    }                                                                                                                                                                                                             
  };                                                                                                                                                                                                              
                                                                                                                                                                                                                  
  const getRecommendations = async (songName, artistName) => {                                                                                                                                                    
    try {                                                                                                                                                                                                         
      setLoading(true);                                                                                                                                                                                           
      setError(null);                                                                                                                                                                                             
      const response = await axios.post(`${API_URL}/recommend`, null, {                                                                                                                                           
        params: {                                                                                                                                                                                                 
          song_name: songName,                                                                                                                                                                                    
          artist_name: artistName,                                                                                                                                                                                
          top_k: 5                                                                                                                                                                                                
        }                                                                                                                                                                                                         
      });                                                                                                                                                                                                         
      setRecommendations(response.data.recommendations);                                                                                                                                                          
    } catch (err) {                                                                                                                                                                                               
      setError('Failed to get recommendations');                                                                                                                                                                  
      console.error(err);                                                                                                                                                                                         
    } finally {                                                                                                                                                                                                   
      setLoading(false);                                                                                                                                                                                          
    }                                                                                                                                                                                                             
  };                                                                                                                                                                                                              
                                                                                                                                                                                                                  
  return (                                                                                                                                                                                                        
    <MusicContext.Provider value={{                                                                                                                                                                               
      searchResults,                                                                                                                                                                                              
      recommendations,                                                                                                                                                                                            
      loading,                                                                                                                                                                                                    
      error,                                                                                                                                                                                                      
      searchSongs,                                                                                                                                                                                                
      getRecommendations                                                                                                                                                                                          
    }}>                                                                                                                                                                                                           
      {children}                                                                                                                                                                                                  
    </MusicContext.Provider>                                                                                                                                                                                      
  );                                                                                                                                                                                                              
}                                                                                                                                                                                                                 
                                                                                                                                                                                                                  
export function useMusic() {                                                                                                                                                                                      
  return useContext(MusicContext);                                                                                                                                                                                
}       
