// src/components/RecommendationsList.js                                                                                                                                                                          
import React from 'react';                                                                                                                                                                                        
import { useMusic } from '../context/MusicContext';                                                                                                                                                               
                                                                                                                                                                                                                  
export function RecommendationsList() {                                                                                                                                                                           
  const { recommendations, loading, error } = useMusic();                                                                                                                                                         
                                                                                                                                                                                                                  
  if (loading) {                                                                                                                                                                                                  
    return <LoadingSpinner />;                                                                                                                                                                                    
  }                                                                                                                                                                                                               
                                                                                                                                                                                                                  
  if (error) {                                                                                                                                                                                                    
    return <ErrorMessage message={error} />;                                                                                                                                                                      
  }                                                                                                                                                                                                               
                                                                                                                                                                                                                  
  return (                                                                                                                                                                                                        
    <div className="max-w-4xl mx-auto">                                                                                                                                                                           
      {recommendations.length > 0 && (                                                                                                                                                                            
        <>                                                                                                                                                                                                        
          <h2 className="text-2xl font-bold mb-6 text-center">                                                                                                                                                    
            Recommended Songs                                                                                                                                                                                     
          </h2>                                                                                                                                                                                                   
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">                                                                                                                                              
            {recommendations.map((song, index) => (                                                                                                                                                               
              <RecommendationCard key={index} song={song} />                                                                                                                                                      
            ))}                                                                                                                                                                                                   
          </div>                                                                                                                                                                                                  
        </>                                                                                                                                                                                                       
      )}                                                                                                                                                                                                          
    </div>                                                                                                                                                                                                        
  );                                                                                                                                                                                                              
}                                                                                                                                                                                                                 
                                                                                                                                                                                                                  
function RecommendationCard({ song }) {                                                                                                                                                                           
  return (                                                                                                                                                                                                        
    <div className="bg-gray-800 rounded-lg p-4 hover:bg-gray-700 transition-colors duration-200">                                                                                                                 
      <h3 className="font-semibold mb-1">{song.track_name}</h3>                                                                                                                                                   
      <p className="text-gray-400 text-sm">{song.artist_name}</p>                                                                                                                                                 
      <p className="text-spotify-green text-sm mt-2">{song.genre}</p>                                                                                                                                             
      <div className="mt-2 bg-gray-900 rounded-full h-2">                                                                                                                                                         
        <div                                                                                                                                                                                                      
          className="bg-spotify-green h-full rounded-full"                                                                                                                                                        
          style={{ width: `${song.similarity_score * 100}%` }}                                                                                                                                                    
        />                                                                                                                                                                                                        
      </div>                                                                                                                                                                                                      
    </div>                                                                                                                                                                                                        
  );                                                                                                                                                                                                              
}                                                                                                                                                                                                                 
                                                                                                                                                                                                                  
function LoadingSpinner() {                                                                                                                                                                                       
  return (                                                                                                                                                                                                        
    <div className="flex justify-center items-center py-12">                                                                                                                                                      
      <div className="animate-spin rounded-full h-12 w-12 border-4 border-spotify-green border-t-transparent" />                                                                                                  
    </div>                                                                                                                                                                                                        
  );                                                                                                                                                                                                              
}                                                                                                                                                                                                                 
                                                                                                                                                                                                                  
function ErrorMessage({ message }) {                                                                                                                                                                              
  return (                                                                                                                                                                                                        
    <div className="text-red-500 text-center py-8">                                                                                                                                                               
      {message}                                                                                                                                                                                                   
    </div>                                                                                                                                                                                                        
  );                                                                                                                                                                                                              
}             
