// src/components/SearchBar.js                                                                                                                                                                                    
import React, { useState } from 'react';                                                                                                                                                                          
import { MagnifyingGlassIcon } from '@heroicons/react/24/solid';                                                                                                                                                  
import { useMusic } from '../context/MusicContext';                                                                                                                                                               
                                                                                                                                                                                                                  
export function SearchBar() {                                                                                                                                                                                     
  const [query, setQuery] = useState('');                                                                                                                                                                         
  const { searchSongs, searchResults, getRecommendations, loading } = useMusic();                                                                                                                                 
                                                                                                                                                                                                                  
  const handleSearch = (e) => {                                                                                                                                                                                   
    e.preventDefault();                                                                                                                                                                                           
    if (query.trim()) {                                                                                                                                                                                           
      searchSongs(query);                                                                                                                                                                                         
    }                                                                                                                                                                                                             
  };                                                                                                                                                                                                              
                                                                                                                                                                                                                  
  const handleSongSelect = (song) => {                                                                                                                                                                            
    getRecommendations(song.track_name, song.artist_name);                                                                                                                                                        
    setQuery('');                                                                                                                                                                                                 
  };                                                                                                                                                                                                              
                                                                                                                                                                                                                  
  return (                                                                                                                                                                                                        
    <div className="max-w-2xl mx-auto mb-8">                                                                                                                                                                      
      <form onSubmit={handleSearch} className="relative">                                                                                                                                                         
        <input                                                                                                                                                                                                    
          type="text"                                                                                                                                                                                             
          value={query}                                                                                                                                                                                           
          onChange={(e) => setQuery(e.target.value)}                                                                                                                                                              
          placeholder="Search for a song or artist..."                                                                                                                                                            
          className="w-full px-4 py-3 rounded-full bg-gray-800 border-2 border-gray-700 focus:border-spotify-green focus:ring-spotify-green text-white placeholder-gray-400"                                      
        />                                                                                                                                                                                                        
        <button                                                                                                                                                                                                   
          type="submit"                                                                                                                                                                                           
          className="absolute right-3 top-1/2 transform -translate-y-1/2"                                                                                                                                         
          disabled={loading}                                                                                                                                                                                      
        >                                                                                                                                                                                                         
          <MagnifyingGlassIcon className="h-6 w-6 text-gray-400" />                                                                                                                                               
        </button>                                                                                                                                                                                                 
      </form>                                                                                                                                                                                                     
                                                                                                                                                                                                                  
      {searchResults.length > 0 && (                                                                                                                                                                              
        <div className="mt-4 bg-gray-800 rounded-lg shadow-xl">                                                                                                                                                   
          {searchResults.map((song, index) => (                                                                                                                                                                   
            <button                                                                                                                                                                                               
              key={index}                                                                                                                                                                                         
              onClick={() => handleSongSelect(song)}                                                                                                                                                              
              className="w-full px-4 py-3 text-left hover:bg-gray-700 transition-colors duration-200 first:rounded-t-lg last:rounded-b-lg"                                                                        
            >                                                                                                                                                                                                     
              <p className="font-semibold">{song.track_name}</p>                                                                                                                                                  
              <p className="text-sm text-gray-400">{song.artist_name}</p>                                                                                                                                         
            </button>                                                                                                                                                                                             
          ))}                                                                                                                                                                                                     
        </div>                                                                                                                                                                                                    
      )}                                                                                                                                                                                                          
    </div>                                                                                                                                                                                                        
  );                                                                                                                                                                                                              
}       
